### ISSUE TITLE
PTY allocation request failed on channel 0

### ISSUE THREAD

**Issue by ccorcos** [duncankl/ssh-mars#4]
Hmm. I'm not sure this is working for me...

```
Are you sure you want to continue connecting (yes/no)? yes
Warning: Permanently added 'mars.vtllf.org,54.153.131.97' (RSA) to the list of known hosts.
Saving password to keychain failed
Saving password to keychain failed
Saving password to keychain failed
Identity added: /Users/chet/.ssh/id_rsa (/Users/chet/.ssh/id_rsa)
PTY allocation request failed on channel 0
https://mars.vtllf.org/signin/gocwcjpbc5uowzn881wa
Connection to mars.vtllf.org closed.
```

I got my password on the 4th try.

Now whenever I try:

```
~ ❯❯❯ ssh mars.vtllf.org                                                       

PTY allocation request failed on channel 0
https://mars.vtllf.org/signin/ouwncqdurmrhswmcyiph
Connection to mars.vtllf.org closed.
```

**Comment by duncankl** [comment]
The message "PTY allocation request failed on channel 0" is just a warning that SSH won't be able to use colors, screen clearing, etc. You can suppress it by using the `-T` flag like this:

    ssh -T mars.vtllf.org

I agree that it's confusing and I'm considering adding that flag to the instructions.

It looks like you did in fact connect successfully because it sent back a signin link. Did either of those links work for you?

**Comment by ccorcos** [comment]
I see. I tried that link, but it failed -- I'll try it again.

It says I'm signed in for a moment, but then its back to the home page -- never got to place my pin...

Super cool idea though btw... Its going to be a pain in the ass to manage all your ssh keys across different platforms though.

**Comment by duncankl** [comment]
Thanks for trying anyway and reporting the problem, sorry it didn't work!
